### ISSUE TITLE
[INVALID] Connecting Bluetooth Devices Crashes Vita

### ISSUE THREAD

**Issue by DerpyBubblez** [cuevavirus/jav#8]
I've been using this for months with wired headphones but I recently got some pretty cheap (but good) bluetooth ones. Connecting them to the Vita with this plugin running; causes the Vita's screen to turn black and I have to restart it.

I've checked two other pairs of bluetooth earbuds and the same thing happens. Any idea what's causing it?

**Comment by cuevavirus** [comment]
Sorry for the delayed response. Can you install this logged version and upload the log at ux0:/jav.txt.
[jav.zip](https://github.com/cuevavirus/jav/files/5205612/jav.zip)

**Comment by DerpyBubblez** [comment]
Sorry I'm late.
[jav.log](https://github.com/cuevavirus/jav/files/5222582/jav.log)

**Comment by cuevavirus** [comment]
It looks like there were 5 attempts to start this plugin. I didn't see anything in the log where the output device is changed so it probably crashed too fast for the log to be flushed. If it doesn't help to start it just once, you could use a real time logging plugin, or I can make it flush more often.

**Comment by DerpyBubblez** [comment]
[jav-logs.zip](https://github.com/cuevavirus/jav/files/5246359/jav-logs.zip)
I connected the device five times in a row, renaming the file after each time the Vita rebooted.

**Comment by cuevavirus** [comment]
Sorry if I wasn't clear, but there were multiple attempts to start this plugin within a single boot. Due to the way this plugin is written, all except one attempt failed, as expected. This shouldn't cause any problems but shouldn't happen anyway. So could you please make it start just once and try it again. Please also connect the BT device without JAV, go into the settings app, find the device in the device settings, and list the available profiles for the device.

The logs this time did show a BT device connecting, although I'm still unable to determine what causes a crash.

**Comment by DerpyBubblez** [comment]
Should I try placing it under MAIN then? Because I haven't had much luck with that, so I end up putting stuff under ALL.

**Comment by cuevavirus** [comment]
you should follow the provided instructions

**Comment by DerpyBubblez** [comment]
I believe the problem has been solved.
I didn't realize that "*main" was case sensitive, so I typed "*MAIN" so it'd be uniform with "*ALL"

After proper setup, the earbuds connect with no problems.
